name: Test

on:
  push:
  schedule:
    - cron: '0 9 * * *'

jobs:
  stable:
    name: Deno Stable
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Setup Deno
      uses: maximousblk/setup-deno@v1

    - name: Run tests
      run: deno run --allow-read --allow-net mod.ts -h

  nightly:
    name: Deno Canary
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - name: Setup Deno
      uses: maximousblk/setup-deno@v1
      with:
        deno-version: canary

    - name: Run tests
      run: deno run --allow-read --allow-net mod.ts -h
